83 fix categories page
Saeed99Madi/MSS-E-Commarce pull request #93
Opened 2023-01-04 21:40 UTC by mahmoudhammad309

2023-01-05 10:04 UTC, Saeed99Madi requested changes

2023-01-10 12:43 UTC, Saeed99Madi requested changes

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/Categories/CategoriesList/ListItem.tsx
> +        style={{
`sx` And `style` !!!!!
`sx` is enough for MUI components for customising styles

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/Categories/CategoriesList/ListItem.tsx
> +                style={{
when the styling take size and more lines in code, its make the code not clean,
then You must convert it to styled component in another file called `components.styled.tsx`,
then u can import it where u want

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/Categories/CategoriesList/SubLIstItem.tsx
> +  ApiServices.init();
when you finish from some review you can resole it by clicking in `Resolve conversation` Button to mark it as resolved review @mahmoudhammad309

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/Categories/UpdateCategory/index.tsx
> +interface Category {
why you have created another Category Interface??

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/Categories/UpdateCategory/index.tsx
> +          style: {
style Props for MUI Component !!!

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/Categories/UpdateCategory/index.tsx
> +            sx={{
Convert the Mui Component to styled component to custom it and import it where u want !

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/DeleteDialog/index.tsx
> +interface Props {
if you don't need to use the Privileges of interface initialling,
I advice you to use `type` instead of `interface` .

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/DeleteDialog/index.tsx
> +  ApiServices.init();
initialize the ApiServices inside the function, that u will use the ApiServices in it.

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/DeleteDialog/index.tsx
> +            style={{
same issue in styling the MUI components

2023-01-10 12:43 UTC, Saeed99Madi commented on dashboard/src/components/dashboard/DeleteDialog/index.tsx
> +            style={{
same issue in styling the MUI components

2023-01-10 17:46 UTC, mahmoudhammad309 commented on dashboard/src/components/dashboard/Categories/UpdateCategory/index.tsx
> +          style: {
this is the way to style the " Dialog MUI component " inner child

2023-01-11 15:00 UTC, Saeed99Madi requested changes

2023-01-12 12:24 UTC, Saeed99Madi approved these changes

2023-01-12 12:26 UTC, merged